{% set version = "1.0.0" %}
{% set sha256 = "11761447c9d869d4028e2f939494649d87ed643eee6283dac7cbed1b5ddb2fb2" %}


package:
  name: greenhill
  version: {{ version }}

source:
  sha256: '{{sha256}}'
  url: https://github.com/ShunOuchi/GreenHill/archive/refs/tags/v1.0.0.tar.gz

build:
  number: 0
  noarch: general

requirement:
  build:
    - make
    - zlib
    - openmp
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - wget
  host:
    - zlib
    - bzip2
    - openmp
  run:
    - zlib
    - gzip
    - bzip2
    - openmp
    - minimap2
test:
  commands:
    - greenhill -h

about:
  home: https://github.com/ShunOuchi/GreenHill
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: A de novo chromosomal-level scaffolding and phasing tool using Hi-C

