{% set version = "1.0.0" %}
{% set sha256 = "9c2d5d3922ff647649258c26e2b08fab4921265e0cfb5072e0d6cd9a0fa1155c" %}


package:
  name: greenhill
  version: {{ version }}

source:
  sha256: '{{sha256}}'
  url: https://github.com/ShunOuchi/GreenHill/archive/refs/tags/v1.0.0.tar.gz

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - zlib
    - bzip2
  run:
    - zlib
    - gzip
    - bzip2
    - minimap2

test:
  commands:
    - greenhill -h

about:
  home: https://github.com/ShunOuchi/GreenHill
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: A de novo chromosomal-level scaffolding and phasing tool using Hi-C
